name: build
on:
  push:
  pull_request:

jobs:
  clang_format:
    name: clang-format
    runs-on: ubuntu-26.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Lint code formatting
        run: |
          clang-format -i *.c *.h
          git diff
          git status --porcelain | grep -q '^ M' && exit 1 || exit 0

  ruff:
    runs-on: ubuntu-26.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Install ruff
        run: sudo pip install ruff

      - name: Lint Python code
        run: ruff check

      - name: Lint Python code formatting
        run: |
          ruff format
          git diff
          git status --porcelain | grep -q '^ M' && exit 1 || exit 0

  check:
    runs-on: ubuntu-26.04
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          path: simvacation
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt install libbsd-dev libjemalloc-dev libssl-dev liblmdb-dev libldap2-dev libcmocka-dev slapd ldap-utils redis-server libhiredis-dev

      - name: Configure slapd
        run: |
          sudo systemctl start slapd
          sudo ldapadd -H ldapi:/// -Y EXTERNAL -f ${{ github.workspace }}/simvacation/test/ldap/local.ldif
          sudo ldapmodify -H ldapi:/// -Y EXTERNAL -f ${{ github.workspace }}/simvacation/test/ldap/config-ubuntu.ldif
          ldapadd -w DrowsyPapa -D "cn=Manager,dc=example,dc=com" -f ${{ github.workspace }}/simvacation/test/ldap/data.ldif

      - name: Install Python dependencies
        run: sudo pip install pytest

      - name: Cache built dependencies
        uses: actions/cache@v6
        id: cache-deps
        with:
          path: ${{ github.workspace }}/.deps
          key: deps-${{ hashFiles('simvacation/.github/workflows/**') }}

      - name: Install fpm
        run: sudo gem install --no-document fpm
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Build libucl
        uses: flowerysong/gh-build-deb@v1
        with:
          src: -b 0.8.1 https://github.com/vstakhov/libucl
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Build urcl
        uses: flowerysong/gh-build-deb@v1
        with:
          src: https://github.com/simta/urcl
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install built dependencies
        run: sudo dpkg -R -i ${{ github.workspace }}/.deps

      - name: Build simvacation
        run: |
          autoreconf -fiv
          CFLAGS='-fprofile-arcs -ftest-coverage' ./configure --with-cmocka
          make -j4 CFLAGS='-Wall -Werror -fprofile-arcs -ftest-coverage'
        working-directory: ${{ github.workspace }}/simvacation

      - name: Test simvacation
        run: make check
        working-directory: ${{ github.workspace }}/simvacation
        env:
          LDAP_SERVER: ldap://localhost/

      - name: Compress test artifacts
        run: |
          tar -caf ${{ github.workspace }}/pytest.tar.zst --ignore-failed-read -C /tmp/pytest-of-runner/pytest-current/ .
          zstd /var/log/mail.log -o ${{ github.workspace }}/mail.log.zst
        if: always()

      - name: Upload test artifacts
        uses: actions/upload-artifact@v7
        with:
          name: pytest
          path: |
            ${{ github.workspace }}/pytest.tar.zst
            ${{ github.workspace }}/mail.log.zst
          retention-days: 7
        if: always()

      - name: Generate coverage reports
        run: gcov *.c
        working-directory: ${{ github.workspace }}/simvacation

      - name: Save code coverage reports
        uses: actions/upload-artifact@v7
        with:
          name: gcov
          path: simvacation/*.gcov

      - name: Build simvacation with clang
        run: |
          make distclean
          CC=clang ./configure
          make -j4 CFLAGS='-Wall -Werror'
        working-directory: ${{ github.workspace }}/simvacation

      - name: Build minimal simvacation
        run: |
          make distclean
          CC=clang CFLAGS='-Wall -Werror' ./configure --without-redis --without-ldap --without-lmdb
          make -j4 CFLAGS='-Wall -Werror'
        working-directory: ${{ github.workspace }}/simvacation
